# -*- coding: utf-8 -*-
"""Assignment_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_iTwIvRE1_RGtj1uLUbUCcH0Dj3W8pIz
"""

#task 1

def even_checker(numeral):
  if numeral%2 == 0:
    print("Even!!")
  else:
    print("Odd!!")
even_checker(5)

#Task 2
def fibonacci(numeral):
  first = 0
  second = 1
  for i in range(numeral):
    if first < numeral:
     print(first,end = " ")
     t = first
     first = second
     second = t + second
fibonacci(10)

#Task 3
def foo_moo(numeral):
  if numeral % 2 == 0 and numeral%3 != 0:
    return "Foo"
  elif numeral % 3 == 0 and numeral%2 !=0:
    return "Moo"
  elif numeral % 2 == 0 and numeral%3 == 0:
    return "FooMoo"
  else:
    return "Boo"
final_result = foo_moo(4)
print(final_result)

print(ord("a"))

#Task 4

def function_name(sentence):
  count_1 = 0
  count_2 = 0
  for i in range(0,len(sentence)):
    if 65<= ord(sentence[i]) <= 90:
      count_1 = count_1 + 1
    elif 97 <= ord(sentence[i]) <= 122:
      count_2 = count_2 + 1
  print("No. of Uppercase characters :",count_1)
  print("No. of Lowercase Characters :",count_2)
function_name('HaRRy PotteR')

#Task 5

age = int(input())
salary = int(input())
designation = input()
designation = designation.upper()
def calculate_tax(n_age,n_salary,n_designation):
  tax = 0
  if n_age < 18 or n_salary < 10000:
    tax = 0
    return tax
  elif n_age >= 18:
    if n_designation == "PRESIDENT":
        tax = 0
        return tax
    else:
      if 10000<= n_salary <= 20000:
        tax = (n_salary*5)/100
        return tax
      else:
        tax = (n_salary*10)/100
        return tax
final_result = calculate_tax(age,salary,designation)
print("The tax:",final_result)

#Task 6
numeral = int(input("PLease enter the number of days:"))
def function_name(n_numeral):
  years = n_numeral//365
  surplus = n_numeral%365
  months = surplus//30
  days = surplus%30
  print(years,"years,",months,"months and",days,"days")
function_name(numeral)

#Task 7

def show_palindrome(numeral):
  a_str=""
  for i in range(1,numeral+1):
     a_str = a_str + str(i)
  for i in range(numeral-1,0,-1):
     a_str = a_str + str(i)
  return a_str
result = show_palindrome(3)
print(result)

#Task 8

def show_palindromic_triangle(numeral):
  for k in range(1,numeral+1):
     for i in range(k,numeral):
       print(" ",end=" ")
     for i in range(1,k+1):
       print(i,end=" ")
     for i in range(i-1,0,-1):
       print(i,end=" ")
     print()
show_palindromic_triangle(3)

#Task 9
import math
def area_circumference_generator(rad_1):
  circum = 2*math.pi*rad_1
  area = math.pi*(rad_1)**2
  return (area, circum)

tuple_1 = area_circumference_generator(1)
print(tuple_1)
print("Area of the circle is",tuple_1[0],"and circumference is",tuple_1[1])

#Task 10

def make_square(starting_point,ending_point):
  n_dict = {}
  for i in range(starting_point,ending_point+1):
    key = i
    value = i**2
    n_dict[key]=value
  return n_dict
make_square(5,9)

#Task 11

def rem_duplicate(a_tuple):
  a_list = list(a_tuple)
  n_list = []
  for i in a_list:
    if i in n_list:
      pass
    else:
      n_list.append(i)
  n_tuple=tuple(n_list)
  return n_tuple
final_result = (rem_duplicate(("Hi", 1, 2, 3, 3, "Hi",'a', 'a', [1,2])))
print(final_result)

#Task 12

def function_name(list_1):
  n_list = []
  for i in list_1:
    if i not in n_list:
       n_list.append(i)
    elif i in list_1:
      n_list.append(i)
  print(list_1)
function_name([1, 2, 3, 3, 3, 3, 4, 5, 8, 8])

def function_name(list_1):
  n_list = []
  counter = 0
  for i in range(len(list_1)):
    if list_1[i] not in n_list:
      if list_1[i] == list_1[i-1]:
         n_list.append(list[i])
         break
      #n_list.append(list_1[i])
      else:
         counter = counter + 1
    n_list.append(list_1[i])
  return n_list
function_name([1, 2, 3, 3, 3, 3, 4, 5, 8, 8])

list_1=[1, 2, 3, 3, 3, 3, 4,4,4, 5, 8, 8]
def function_name(elements):
  list_t=[]
  for values in elements:
    if list_t.count(values) < 2:
      list_t.append(values)
  return list_t

current=function_name(list_1)
print(current)

#Task 12(mine)
def function_name(list_1):
  n_list = []
  counter = 0
  for i in list_1:
    if n_list.count(i) < 2:
      n_list.append(i)
    else:
      counter = counter + 1
  return counter, n_list
result = function_name([1, 2, 3, 3, 3, 3, 4, 5, 8, 8])
print("Removed:",result[0])
print(result[1])

#Task 13

first = input("Enter the operator:")
second = float(input("The first number:"))
third = float(input("The first number:"))
def function_name(n_first,n_second,n_third):
 if n_first == "+":
   result = n_second + n_third
 elif n_first == "-":
   result = n_second - n_third
 elif n_first == "*":
   result = n_second * n_third
 elif n_first == "/":
   result = n_second / n_third
 return result
f_result = function_name(first,second,third)
print("The final result:",f_result)

def operation(operator, num1,num2):
    if (operator == '+'):
        return num1+num2
    elif(operator == '-'):
        return num1-num2
    elif(operator == '/'):
        return num1/num2
    elif(operator == '*'):
        return num1*num2

operator = input("Enter an operator: ")
num1 = float(input("Enter 1st num: "))
num2 = float(input("Enter 2nd num: "))
print("Result is:",operation(operator,num1,num2))

#Task 14

sentence_1 = input()
position_1 = int(input())
def function_name(n_sentence,n_position):
  str_1 = n_sentence[0]
  str_2 = ""
  for i in range(1,len(n_sentence)):
      if i%n_position == 0:
        str_2 = str_2 + n_sentence[i]
      else:
        str_1 = str_1 + n_sentence[i]
  f_str = str_1 + str_2
  return f_str

final = function_name(sentence_1,position_1)
print(final)

sentence_1 = input()
position_1 = int(input())
def function_name(n_sentence,n_position):
  str_1 = n_sentence[0]
  str_2 = ""
  for i in range(1,len(n_sentence)):
      if i%n_position != 0:
        str_1 = str_1 + n_sentence[i]
      else:
        str_2 = str_2 + n_sentence[i]
  f_str = str_1 + str_2
  return f_str

final = function_name(sentence_1,position_1)
print(final)

#Task 15

numeral = int(input("Enter the items number:"))
order_items = []
for i in range(0,numeral):
  items = input()
  order_items.append(items)
create_dict = {'Rice':105,'Potato':20,'Chicken':250,'Beef':510,'Oil':85}
def function_name(own_list,location = 'Dhanmondi'):
  total = 0
  for i in range(0,len(own_list)):
    total = total + create_dict[own_list[i]]
  if location == 'Dhanmondi':
    total = total + 30
  else:
    total = total + 70

  return total
final = (function_name(order_items,'Mohakhali'))
print(final)

def cart_price(order_items, location="Dhanmondi"):
    stocks = {"Rice": 105, "Potato": 20, "Chicken": 250, "Beef": 510, "Oil": 85}

    total = 0
    final = 0
    for i in order_items:
        if i in stocks.keys():
            total = total + stocks[i]
            if location == "Dhanmondi":
                final = total + 30
            else:
                final = total + 70
    return final


print(cart_price(["Rice", "Beef", "Rice"]))

#Task 16
x = 0
y = 0
sum = 0
p = 0.0
while (x < 9):
  y = x/2
  while (y<x):
    p = (x + 5.0)/ 2
    sum = sum+2 + x + y*2 + int(p)
    print(sum)
    y=y+1
  x = x+2
  if (x>5):
    sum = 2
  else:
    sum += 3

x = 0
y = 0
sum = 0
while (x < 10):
  y = x - 3
  y = 40
  while (y > 22):
    if ((sum > 30) and (sum < 40)):
       sum = sum + x * 2
    elif((sum > 40) and (sum < 50)):
       sum = sum + x * 3
    else:
       sum = sum + 23
    print(sum)
    y = y - 10
  x += 2

#Task 2

limit=int(input('please enter the limit: '))
def fibonacci(limit_t):

  first=0
  second=1
  print(first,end=' ')
  print(second,end=' ')
  third=first+second
  while third<=limit_t:
    print(third,end=' ')
    first=second
    second=third
    third=first+second

fibonacci(limit)

#Task 5
age=int(input('please enter the age: '))
salary=float(input('please enter the salary: '))
job_designation=input('please enter the designation: ')

if job_designation=='president':
  presidency=1
else:
  presidency=0

def calculate_tax(the_age,the_salary,the_designation):
  if the_age<18 or presidency==1 or the_salary<1000:
    print('your tax is 0')
  elif the_salary>=10000 and the_salary<=20000:
    tax=(the_salary*5)/100
    print('your tax:',tax)
  elif the_salary>20000:
    tax=(the_salary*10)/100
    print('your tax:',tax)

calculate_tax(age,salary,job_designation)

#Task 18
x = y = 0
sum = 0
while (x < 10):
 y = x - 3
 while (y < 3):
   sum = x - y * 2
   print(sum)
   y = y + 1
 if (x > 7):
   x += 1
 else:
   x += 3
sum = x - y * 2
print(sum)

#Task 19

x = 0
p = 0
sum = 0
p = 1
x = 2
q = 0.0
sum = 0
while (p < 12):
   q = x + p - (sum + int(5 / 3)) / 3.0 % 2
   sum = sum + x + int(q)
   x+=1
   print(sum)
   if (x > 5):
     p += int(4 / 2)
   else:
     p += 3 % 1
sum = sum + p
print(sum)

0 + 2 + 0 + *2 + 3

4/2

p=1
p += 3 % 1
print(p)

1%3/2

0.33%2

-5//2

#Task 20

i = 2
j = 0
k = 17
test = "-->dog"
while i < 7:
  k-=1
  j = k
  while j > 12:
    if (j % 2 == 0):
      test += "<--"
      test = test + str(i) + str(j // 2)
    else:
      test += "-->"
      test = test + str(i // 2) + str(j)
    print(test)
    j-=1
  i+=1

14//3

#Task 21

test = ""
i = 5
j = 0
k = 15
while (i< 10):
  k-=1
  j = k
  while (j > 10 ):
    if j % 2 == 0:
      test = "<--"
      test = test + str(i) + '3' + "-->" + str(j // 3)
    else:
      test = "-->"
      test = "-->" + str((i // 3)) + test + str(j)
    print(test)
    j -=1
  i+=1

" == "

#Task 22

i = 10
while(i >= -20):
  if(i < 0):
    test = " != "
    test = str(i//2) + test + str(int(i/2))
  else:
    test = " == "
    test = str(i//2) + test + str(int(i/2))
  print(test)
  i -= 5

int(-5/2)
-5//2

input_user = input()
list_1 = input_user.split(",")